language: r
warnings_are_errors: true
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - testthat

script:
  - make install
  - make check
  - make test
